# Tutorial Exercise: Yelp reviews

## Introduction

This exercise uses a small subset of the data from Kaggle's [Yelp Business Rating Prediction](https://www.kaggle.com/c/yelp-recsys-2013) competition.

**Description of the data:**

- **`yelp.csv`** contains the dataset. It is stored in the repository (in the **`data`** directory), so there is no need to download anything from the Kaggle website.
- Each observation (row) in this dataset is a review of a particular business by a particular user.
- The **stars** column is the number of stars (1 through 5) assigned by the reviewer to the business. (Higher stars is better.) In other words, it is the rating of the business by the person who wrote the review.
- The **text** column is the text of the review.

**Goal:** Predict the star rating of a review using **only** the review text.

**Tip:** After each task, I recommend that you check the shape and the contents of your objects, to confirm that they match your expectations.

## Task 1

Read **`yelp.csv`** into a pandas DataFrame and examine it.

In [2]:
import pandas as pd
df = pd.read_csv('data\yelp.csv')
df.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
2  love the gyro plate. Rice is so good and I als...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2  0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0

## Task 2

Create a new DataFrame that only contains the **5-star** and **1-star** reviews.

- **Hint:** [How do I apply multiple filter criteria to a pandas DataFrame?](http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb#9.-How-do-I-apply-multiple-filter-criteria-to-a-pandas-DataFrame%3F-%28video%29) explains how to do this.

In [3]:
df2 = df[(df['stars']==5) | (df['stars']==1)]
df2.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
6  zp713qNhx8d9KCJJnrw1xA  2010-02-12  riFQ3vxNpP4rWLk_CSri2A      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   
6  Drop what you're doing and drive here. After I...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
6  wFweIWhv2fREZV_dYkz_1g     7       7      4

In [4]:
print(df.shape)
print(df2.shape)

(10000, 10)
(4086, 10)


## Task 3

Define X and y from the new DataFrame, and then split X and y into training and testing sets, using the **review text** as the only feature and the **star rating** as the response.

- **Hint:** Keep in mind that X should be a pandas Series (not a DataFrame), since we will pass it to CountVectorizer in the task that follows.

In [6]:
X = df2.text
y = df2.stars
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3064,)
(1022,)
(3064,)
(1022,)


## Task 4

Use CountVectorizer to create **document-term matrices** from X_train and X_test.

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)
X_train_dtm

<3064x16823 sparse matrix of type '<class 'numpy.int64'>'
	with 239078 stored elements in Compressed Sparse Row format>

## Task 5

Use multinomial Naive Bayes to **predict the star rating** for the reviews in the testing set, and then **calculate the accuracy** and **print the confusion matrix**.

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains how to interpret both classification accuracy and the confusion matrix.

In [8]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred = nb.predict(X_test_dtm)
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.909980430528
[[122  79]
 [ 13 808]]


## Task 6 (Challenge)

Calculate the **null accuracy**, which is the classification accuracy that could be achieved by always predicting the most frequent class.

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains null accuracy and demonstrates two ways to calculate it, though only one of those ways will work in this case. Alternatively, you can come up with your own method to calculate null accuracy!

In [9]:
print(y_train.value_counts().iloc[0] / len(y_train))

0.821148825065


## Task 7 (Challenge)

Browse through the review text of some of the **false positives** and **false negatives**. Based on your knowledge of how Naive Bayes works, do you have any ideas about why the model is incorrectly classifying these reviews?

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains the definitions of "false positives" and "false negatives".
- **Hint:** Think about what a false positive means in this context, and what a false negative means in this context. What has scikit-learn defined as the "positive class"?

In [11]:
FP = X_test[y_test < y_pred]
print(FP.head())

4595    I have been here once for lunch and sat outsid...
7112    The staff is friendly. But the physical hotel ...
715     What's with the cheese?  It isn't even Velveta...
1963                       Prices are often way too high!
6584    Jimmy Johns is cheaper and better ... The Capr...
Name: text, dtype: object


In [12]:
print(X_test[4595])

I have been here once for lunch and sat outside only to get eaten alive by flies, nothing worse than eating outside on a nice patio and being pestered the entire time. 

I decided to give it another chance for happy hour, well guess what? flies followed me inside too. 

I don't know if it was the time of year (early spring) or what, but they really need an exterminator!


## Task 8 (Challenge)

Calculate which 10 tokens are the most predictive of **5-star reviews**, and which 10 tokens are the most predictive of **1-star reviews**.

- **Hint:** Naive Bayes automatically counts the number of times each token appears in each class, as well as the number of observations in each class. You can access these counts via the `feature_count_` and `class_count_` attributes of the Naive Bayes model object.

In [14]:
token = vect.get_feature_names()
print(len(token))
features = nb.feature_count_
print(nb.feature_count_.shape)

16823
(2, 16823)


In [15]:
tokens = pd.DataFrame({'token': token, 'one': features[0], 'five': features[1]}).set_index('token')
tokens.head()

five   one
token            
00     36.0  30.0
000     8.0   3.0
00a     0.0   1.0
00am    2.0   2.0
00pm    6.0   0.0

In [16]:
tokens += 1
tokens.head()

five   one
token            
00     37.0  31.0
000     9.0   4.0
00a     1.0   2.0
00am    3.0   3.0
00pm    7.0   1.0

In [17]:
tokens.one = tokens.one / nb.class_count_[0]
tokens.five = tokens.five / nb.class_count_[1]
tokens['five ratio'] = tokens.five / (tokens.five + tokens.one)
tokens.head()

five       one  five ratio
token                                
00     0.014706  0.056569    0.206325
000    0.003577  0.007299    0.328888
00a    0.000397  0.003650    0.098208
00am   0.001192  0.005474    0.178851
00pm   0.002782  0.001825    0.603904

In [18]:
tokens.sort_values('five ratio', ascending=False)

five       one  five ratio
token                                         
flavors         0.044913  0.001825    0.960956
fantastic       0.075517  0.003650    0.953899
perfect         0.096582  0.007299    0.929734
yum             0.023847  0.001825    0.928919
favorite        0.130763  0.010949    0.922738
perfection      0.018680  0.001825    0.911007
bianco          0.017488  0.001825    0.905513
gluten          0.017091  0.001825    0.903528
casual          0.016693  0.001825    0.901457
brunch          0.016693  0.001825    0.901457
gem             0.016296  0.001825    0.899296
view            0.016296  0.001825    0.899296
pasty           0.015898  0.001825    0.897037
fruit           0.015103  0.001825    0.892202
mozzarella      0.015103  0.001825    0.892202
authentic       0.029809  0.003650    0.890922
south           0.014706  0.001825    0.889610
rooms           0.014308  0.001825    0.886891
amazing         0.185215  0.023723    0.886461
organic         0.013911  0.001825    0.884034
awesome         0.119634  0.016423    0.879291
waffles         0.013116  0.001825    0.877864
excellent       0.104928  0.014599    0.877864
pleased         0.013116  0.001825    0.877864
dentist         0.013116  0.001825    0.877864
creative        0.013116  0.001825    0.877864
loved           0.065183  0.009124    0.877211
affordable      0.012719  0.001825    0.874526
die             0.025040  0.003650    0.872788
superb          0.012321  0.001825    0.871001
...                  ...       ...         ...
actions         0.000397  0.010949    0.035029
hire            0.000397  0.010949    0.035029
pointing        0.000397  0.010949    0.035029
bitter          0.000397  0.010949    0.035029
claimed         0.000397  0.010949    0.035029
gratuity        0.000397  0.010949    0.035029
canal           0.000397  0.010949    0.035029
spilled         0.000397  0.010949    0.035029
blowdry         0.000397  0.010949    0.035029
disaster        0.000397  0.010949    0.035029
worst           0.003975  0.122263    0.031485
innova          0.000397  0.012774    0.030176
pischke         0.000397  0.012774    0.030176
unfriendly      0.000397  0.012774    0.030176
nibbles         0.000397  0.012774    0.030176
filthy          0.000397  0.012774    0.030176
gringos         0.000397  0.012774    0.030176
yuck            0.000795  0.025547    0.030176
horrible        0.003975  0.133212    0.028972
fuse            0.000397  0.014599    0.026504
voucher         0.000397  0.014599    0.026504
unacceptable    0.000397  0.014599    0.026504
ants            0.000397  0.014599    0.026504
acknowledged    0.000397  0.014599    0.026504
boca            0.000397  0.014599    0.026504
disgusting      0.001192  0.047445    0.024515
rudely          0.000397  0.016423    0.023629
unprofessional  0.000397  0.016423    0.023629
refused         0.000397  0.020073    0.019416
ugh             0.000397  0.029197    0.013430

[16823 rows x 3 columns]

## Task 9 (Challenge)

Up to this point, we have framed this as a **binary classification problem** by only considering the 5-star and 1-star reviews. Now, let's repeat the model building process using all reviews, which makes this a **5-class classification problem**.

Here are the steps:

- Define X and y using the original DataFrame. (y should contain 5 different classes.)
- Split X and y into training and testing sets.
- Create document-term matrices using CountVectorizer.
- Calculate the testing accuracy of a Multinomial Naive Bayes model.
- Compare the testing accuracy with the null accuracy, and comment on the results.
- Print the confusion matrix, and comment on the results. (This [Stack Overflow answer](http://stackoverflow.com/a/30748053/1636598) explains how to read a multi-class confusion matrix.)
- Print the [classification report](http://scikit-learn.org/stable/modules/model_evaluation.html#classification-report), and comment on the results. If you are unfamiliar with the terminology it uses, research the terms, and then try to figure out how to calculate these metrics manually from the confusion matrix!

In [19]:
X = df.text
y = df.stars
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500,)
(2500,)
(7500,)
(2500,)


In [20]:
vect = CountVectorizer()
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)
X_train_dtm

nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred = nb.predict(X_test_dtm)
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.4844
[[ 61  22  17  65  18]
 [ 15  14  49 146  22]
 [  3  14  30 280  28]
 [ 11   1  19 678 202]
 [  5   1  10 361 428]]


In [21]:
print(y_train.value_counts().max() / len(y_train))

0.348666666667


In [22]:
print(metrics.classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          1       0.64      0.33      0.44       183
          2       0.27      0.06      0.09       246
          3       0.24      0.08      0.12       355
          4       0.44      0.74      0.56       911
          5       0.61      0.53      0.57       805

avg / total       0.47      0.48      0.44      2500



In [23]:
print(df.sort_values('stars', inplace=True))
print(df.head(4))

None
                 business_id        date               review_id  stars  \
3456  0VLZj0f3llL9IkL5GOT3lg  2011-10-26  tuNdSzBSNmcwUXHLY0re0A      1   
1747  eGj1NnvbIUVWgDYQWEOwQg  2012-06-10  MEzqi22MaWQV1LMSSPmh6Q      1   
5543  kJFS_3WlP6TFdNUYt6V6FA  2011-09-26  mSB78PqDRD7jE5g4yZuaMQ      1   
4934  e8FMAuTswDueAlLsNyLhcA  2010-02-11  4vvdwQyS5uCSo74iw81irw      1   

                                                   text    type  \
3456  My husband and I went there for our first time...  review   
1747  This dog park gets one star.Why?Because the la...  review   
5543  This review is for the bar only.\nI had a date...  review   
4934  I'd have to disagree with the person who said ...  review   

                     user_id  cool  useful  funny  
3456  E8FSWBUXArSJU7cWpBXF7Q     0       0      0  
1747  qBAaWZxyuFnSZU0NzFlNDw     0       0      0  
5543  AYGHNy8gPxl2Q-etTT3hZw     2       6      6  
4934  W5Pd_GmMem2LdHZkoxQCtw     0       0      0  
